# Generated by Django 3.1.2 on 2024-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('compania', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado_provincia', models.CharField(max_length=100)),
                ('postal', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('numero_compra', models.IntegerField(unique=True)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio_producto', models.IntegerField()),
                ('cantidad', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
