# Generated by Django 3.1.2 on 2024-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240605_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='id',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='numero_compra',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
