# Generated by Django 3.1.2 on 2024-07-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ordencompra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('nombre_cliente', models.CharField(max_length=100)),
                ('compania', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado_provincia', models.CharField(max_length=100)),
                ('postal', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('numero_compra', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio_producto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MotivoRechazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos_rechazo', to='app.entrega')),
            ],
        ),
    ]
