# Generated by Django 3.1.2 on 2024-07-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_motivorechazo_orden_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivorechazo',
            name='motivo',
            field=models.TextField(default='Sin motivo especificado'),
        ),
    ]
