# Generated by Django 3.1.2 on 2024-07-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240716_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('entrega', 'Entrega'), ('rechaza', 'Rechaza'), ('por entregar', 'Por Entregar'), ('anulado', 'Anulado')], default='por entregar', max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='motivorechazo',
            name='orden_compra',
        ),
        migrations.AlterField(
            model_name='motivorechazo',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada'), ('rectificada', 'Rectificada'), ('entregada', 'Entregada')], default='creada', max_length=11),
        ),
    ]
